project_id = "slgspsdbjjucuzrtgxtf"

[functions.create-payment]
verify_jwt = false

[functions.create-driver-subscription]
verify_jwt = false

[functions.check-driver-subscription]
verify_jwt = false

[functions.driver-customer-portal]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.admin-driver]
verify_jwt = false
verify_jwt = false
